### ISSUE TITLE
HTTPS not working if multiple sitemaps are generated

### ISSUE THREAD

**Issue by cmartin6** [dmitryd/typo3-dd_googlesitemap#104]
Typo3 8.7.30

The extension is configured with multiple SSL eID script URLs (https://), and generates one xml file with sitemapindexes of the other sitemaps. The sitemapindexes are correct with https, but the actual linked sitemaps contain http instead of https.

**Comment by dmitryd** [comment]
The extension uses TYPO3 to generate links. It does not add schema on its own. So there is something inside your setup that makes TYPO3 think it is on http. Are you running behind a reverse proxy?

**Comment by dmitryd** [comment]
No feedback provided.
