### ISSUE TITLE
Support for "news" extension

### ISSUE THREAD

**Issue by hacksch** [dmitryd/typo3-dd_googlesitemap#31]
Hello Dmitry,

please add a generator for the news extension too. (http://typo3.org/extensions/repository/view/news/)

Here my file depends on your tt_news generator:
https://docs.google.com/document/d/1xqgg8JOUttxghvrnihFabVLmCH53xRtQQulvT8YWccY/edit?usp=sharing

**Comment by BastianBalthasarBux** [comment]
1. there is a seperate extension existing, providing a tx_news sitemap, dd_googlesitemap_dmf.
2. this extension is errornous, as it generates detail-page-links to news-articles of type internal-page.

All this said over a year later, sry for that. ;)

**Comment by jousch** [comment]
Additionally @georgringer has implemented support for EXT:dd_googlesitemap directly in [EXT:news](https://github.com/georgringer/news/blob/master/Classes/Hooks/TxNewsSitemapGenerator.php)

**Comment by jousch** [comment]
I think therefore this issue can be closed for now?
