### ISSUE TITLE
Make link object configurable via typoscript

### ISSUE THREAD

**Issue by dmitryd** [dmitryd/typo3-dd_googlesitemap#4]
When creating news sitemaps it might be cool to have month and year parameters encoded into the resulting realurl. to be able to achieve that a configurable typolink setting via typoscript instead of a hard coded array would be nice.

Something like that:

``` typoscript
tx_ddgooglesitemap.newsLink = TEXT
tx_ddgooglesitemap.newsLink {
   typolink.forceAbsoluteUrl = 1
   typolink.returnLast = url
   typolink.parameter.field = singlePid
   typolink.additionalParams.cObject = COA
   typolink.additionalParams.cObject {
      10 = TEXT
      10.wrap = &tx_ttnews[tt_news]=|
      10.field = uid
      20 = TEXT
      20.wrap = &tx_ttnews[month]=|
      20.field = datetime
      20.strftime = %m
      30 = TEXT
      30.wrap = &tx_ttnews[year]=|
      30.field = datetime
      30.strftime = %y
   }
}
```

Imported from Forge: http://forge.typo3.org/issues/47059

**Comment by helmut-winkelbach** [comment]
Hi Dimitry,
what do i wrong with the implementation for tx_news (latest versions of all) as the news aren't shown up in the sitemap?
http://www.bahai.by/index.php?eID=dd_googlesitemap

How should i change the script above?

Thanks for your support
Helmut

**Comment by dmitryd** [comment]
dd_googlesitemap works with tt_news, not tx_news.

**Comment by helmut-winkelbach** [comment]
dd_googlesitemap_dmf did it!

You need the version on githup which is for TYPO3 CMS 6.2
https://github.com/dohomi/dd_googlesitemap_dmf

Thanks
