### ISSUE TITLE
exclude pages and subpages

### ISSUE THREAD

**Issue by derBoogie** [dmitryd/typo3-dd_googlesitemap#41]
I would appreciate it if there was a way, to exclude pages with their subpages, using the page IDs in TS Setup.

Here is my workaround (tested in TYPO3 v4.7):

TS-Setup: tx_ddgooglesitemap.excludePages = 9,38,47,...

File: typo3conf\ext\dd_googlesitemap\class.tx_ddgooglesitemap_pages.php

Added code to function __construct():

$excludePages = t3lib_div::intExplode(',', $GLOBALS['TSFE']->tmpl->setup['tx_ddgooglesitemap.']['excludePages'], TRUE);
if (count($excludePages) > 0) {
    $this->excludedPages = $excludePages;
    // get subpages
    $oSysPage = t3lib_div::makeInstance('t3lib_pageSelect');
    $oSysPage->init(true);
    $aSubpages = array();
    foreach ($this->excludedPages AS $iPageID) {
    $this->subPages($oSysPage, $aSubpages, $iPageID);
    }
    $this->excludedPages = array_merge($this->excludedPages,$aSubpages);
    unset($aSubpages);  
}

Added function:
private function subPages(&$oSysPage, &$aSubpages, $iPageID) {
    $aSubpagesTemp = $oSysPage->getMenu($iPageID);  
    foreach ($aSubpagesTemp AS $aPage) {
        $aSubpages[] = $aPage['uid'];
        $this->subPages($oSysPage, $aSubpages, $aPage['uid']);
    }
    unset($aSubpagesTemp);  
}

greets Boogie

**Comment by tbrodard** [comment]
I agree with "So if you do not want the page in the sitemap, you do not want it in search and vice versa", but if a page with a plugin that display detail of items (eg News, Agenda, ...), this page has to be indexed by TYPO3.

**Comment by dmitryd** [comment]
For news there has to be a separate sitemap. It is implemented already.

**Comment by robinson2** [comment]
If a separate sitemap is used for the news, the news details page still has to be excluded from the regular sitemap. The exclude from search checkbox is not an option in this case, because it prevents all news from beeing indexed by the indexed search engine.
