### ISSUE TITLE
PHP Fatal error:  Class 'DmitryDulepov\DdGooglesitemap\Scheduler\Task' not found in typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4484

### ISSUE THREAD

**Issue by felixsemmler** [dmitryd/typo3-dd_googlesitemap#51]
Please rename folder Classes/scheduler to Classes/Scheduler to fix TYPO3 autoloading issue for classes in folder scheduler. This bug issue occurs in TYPO3 6.2.12.

**Comment by dmitryd** [comment]
Fixed.
