### ISSUE TITLE
TYPO3 7 LTS: Unknown type: select in BE

### ISSUE THREAD

**Issue by Gorli** [dmitryd/typo3-dd_googlesitemap#61]
In the

ext_tables.php

'type' => 'Select'

by

'render type' => 'SELECT SINGLE'

be supplemented!

greeting

Harald

**Comment by dmitryd** [comment]
Fixed [here](https://github.com/dmitryd/typo3-dd_googlesitemap/commit/ca1237a739f2a85e530d8a475ce2f393bba0500e).
