### ISSUE TITLE
dd_googlesitemap path as pid instead of realurl name

### ISSUE THREAD

**Issue by sheydin** [dmitryd/typo3-dd_googlesitemap#63]
Hallo Dmitry,

your exension dd_googlesitemap first showed speaking URLs via realURL, some time later it shows the IDs instead of the speaking URLs. The configuration has been as follows and did not change:

page.config {
	simulateStaticDocuments = 0
	baseURL = http://memedix.de/
	tx_realurl_enable = 1
}

Here is the sitemap: http://memedix.de/?eID=dd_googlesitemap

TYPO3 7.6.2 + realURL 1.13.5 + dd_googlesitemap 2.0.4

Do you have any idea how to fix this?

Thank you for your work for the T3 Community! Appreciate it very much!

**Comment by dmitryd** [comment]
Sitemap looks ok now.
