### ISSUE TITLE
set change frequency manually

### ISSUE THREAD

**Issue by hannesbochmann** [dmitryd/typo3-dd_googlesitemap#64]
It would be great if the change frequency of a page could be set manually through a database field. If the field is set than the change frequency is not calculated but taken directly from the page record.

I need this enhancement since I have pages where dynamic list of datasets are displayed. The pages themselves won't be changed often resulting in a calculated change frequency of monthly or yearly as the datasets don't reside directly on the page. But as the content is dynamically and changes often those pages need a much higher frequency. The only solution I found would be to add a new field for this. Would you mind if I provide an enhancement for this as a pull request or is there a more simple solution?

P.S. I could also add own sitemaps for the several dynamic datatypes but I think being able to set a manual change frequency would be a faster solution.

**Comment by dmitryd** [comment]
Yes, you can make a pull request but it should also have a default "Auto" option to keep compatible behavior for all existing installations.

Thanks!
