### ISSUE TITLE
No generator found for type 'news'

### ISSUE THREAD

**Issue by haurg** [dmitryd/typo3-dd_googlesitemap#66]
I receive the issue "No generator found for type 'news'" when showing http://www.xxx.com/?eID=dd_googlesitemap&sitemap=news&pidList=32&singlePid=25

The following paramaters are set to: forceStartPid = 3

Page structure is as follows:

Home (shortcut
- Home
- xxx
- single view (tt_news) (id=25)
- news (sysfolder) (id=32)

Thanks for fixing that issue.

Best

**Comment by dmitryd** [comment]
Use `sitemap=tt_news`
