### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by ogrosko** [dmitryd/typo3-dd_googlesitemap#69]
Installing plugin via composer I'm getting following warning:

> Warning: Ambiguous class resolution, "DmitryDulepov\DdGooglesitemap\Scheduler\Task" was found in both "/var/www/vhosts/dev.digitalwerk.at/wsw.dev.digitalwerk.at/typo3conf/ext/dd_googlesitemap/Classes/scheduler/Task.php" and "/var/www/vhosts/dev.digitalwerk.at/wsw.dev.digitalwerk.at/typo3conf/ext/dd_googlesitemap/Classes/Scheduler/Task.php", the first will be used.
Warning: Ambiguous class resolution, "DmitryDulepov\DdGooglesitemap\Scheduler\AdditionalFieldsProvider" was found in both "/var/www/vhosts/dev.digitalwerk.at/wsw.dev.digitalwerk.at/typo3conf/ext/dd_googlesitemap/Classes/scheduler/AdditionalFieldsProvider.php" and "/var/www/vhosts/dev.digitalwerk.at/wsw.dev.digitalwerk.at/typo3conf/ext/dd_googlesitemap/Classes/Scheduler/AdditionalFieldsProvider.php", the first will be used.

**Comment by ogrosko** [comment]
Hmm now I'm getting following error

`  - Removing typo3-ter/dd-googlesitemap (2.0.5)
  - Installing typo3-ter/dd-googlesitemap (2.0.6)
    Downloading: 100%         

                              
  [ErrorException]            
  Undefined index: conflicts`

**Comment by zauni** [comment]
This error is also visible if you are trying to install it for the first time.
```
  - Installing typo3-ter/dd-googlesitemap (2.0.6)
    Downloading: 100%
    Downloading: 100%

  [ErrorException]
  Undefined index: conflicts
```
Strange that the string "conflicts" is just in the ext_emconf.php file, but it looks okay there...

**Comment by ogrosko** [comment]
With version 2.0.5 it wasn't problem

**Comment by Lemmork** [comment]
I ran into the same issue.

It turns out, that if you install Version 2.0.6 directly from typo3 TER there is an error in the extconf:
`array (
      'typo3' => '6.2.0-7.6.999',
      '' => '',
    ),
    'conflicts' => 
    array (
    ),`

This is not if you require the version directly from github:
`"dmitryd/typo3-dd-googlesitemap": "2.0.6",`

So I think this is not an error of the extension, but of typo3_ter

**Comment by ogrosko** [comment]
Yes @Lemmork you are right, with 

`"dmitryd/typo3-dd-googlesitemap": "2.0.6",`

it works with no problems

**Comment by dmitryd** [comment]
I believe the problem is on the TYPO3 composer repository. I cannot really do anything about it. Just use `dmitryd/typo3-dd-googlesitemap`.
