### ISSUE TITLE
typo3 v7.6.12: URL is wrong by using RealURL

### ISSUE THREAD

**Issue by webfacer** [dmitryd/typo3-dd_googlesitemap#76]
Hi,

if i build my URL with RealURL (my realurl config):

    $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl'] = [
    
        #'encodeSpURL_preProc' => ['Repromedia\\RmedRealurlConfig\\Hooks\\Encoding->run'],
        'decodeSpURL_preProc' => ['Repromedia\\RmedRealurlConfig\\Hooks\\UrlRedirect->redirect'],
    
        '_DEFAULT' => [
    
            'init' => [
                'enableCHashCache' => 1,
                'appendMissingSlash' => 'ifNotFile,redirect',
                'enableUrlDecodeCache' => 1,
                'enableUrlEncodeCache' => 1,
                'postVarSet_failureMode' => '',
            ],
    
            'pagePath' => [
                'type' => 'user',
                'userFunc' => 'EXT:realurl/class.tx_realurl_advanced.php:&tx_realurl_advanced->main',
                'spaceCharacter' => '-',
                'languageGetVar' => 'L',
                'expireDays' => 7,
                'rootpage_id' => 19051,
                'firstHitPathCache' => 1,
            ],
    
            'preVars' => [
                # language translation
                /*[
                    'GETvar' => 'L',
                    'valueMap' => [
                        'de' => '0',
                        'en' => '1',
                    ],
                    'valueDefault' => 'de',
                    'noMatch' => 'bypass',
                ],*/
            ],
    
            'fixedPostVars' => [],
    
            'postVarSets' => [
                '_DEFAULT' => [
                    'init' => [
                        'enableCHashCache' => 1,
                        #'appendMissingSlash' => 'ifNotFile,redirect',
                        'enableUrlDecodeCache' => 0,
                        'enableUrlEncodeCache' => 0,
                        'postVarSet_failureMode' => '',
                    ],
    
    
                    # this block shows friendly pagination
                    'pages' => [
                        ['GETvar' => 'tx_rmedpage_showcase[@widget_0][currentPage]',],
                    ],
    
                    # this block shows friendly title of detail page, without controller, just the action segment
                    # example.: http://example.com/category/detail/page-title
                    'detail' => [
                        [
                            'GETvar' => 'tx_rmedpage_showcase[id]',
                            'lookUpTable' => [
                                'table' => 'pages',
                                'id_field' => 'uid',
                                'alias_field' => 'title',
                                'addWhereClause' => ' AND NOT deleted',
                                'useUniqueCache' => '1',
                                'useUniqueCache_conf' => [
                                    'strtolower' => '1',
                                    'spaceCharacter' => '-',
                                ],
                            ],
                        ],
    
                        [
                            'GETvar' => 'tx_rmedpage_showcase[controller]',
                            'valueMap' => [
                                'news' => '',
                            ],
                            'noMatch' => 'bypass',
                        ],
    
                        [
                            'GETvar' => 'tx_rmedpage_showcase[action]',
                            'valueMap' => [
                                'detail' => '',
                            ],
                            'noMatch' => 'bypass'
                        ],
                    ],
                ],
            ],
        ],
    ];

this config creates this url "example.com/parentPage/detail/currentSubPage".
but when i call the googlesitemap it doesn´t set the section "detail" which is defined in RealURL.

example output of googlesitemap -> "example.com/parentPage/currentSubPage"
Do i need to configure something for googlestiemap?

I will need this section of the URL for RealURL to know which method is called.

**Comment by dmitryd** [comment]
Please, ask questions in TYPO3 mailing lists or Slack.
