### ISSUE TITLE
Wrong name scheduler folder on composer

### ISSUE THREAD

**Issue by Zillion01** [dmitryd/typo3-dd_googlesitemap#78]
When using typo3-ter composer on Ubuntu it will install 2 class folders 'Scheduler' and 'scheduler'. Also see SLACK 23 januari 14:23u for more info.

<img width="911" alt="schermafbeelding 2017-01-23 om 14 31 32" src="https://cloud.githubusercontent.com/assets/1055822/22205807/b285aada-e178-11e6-94dc-db4cb1bd72b0.png">

**Comment by dmitryd** [comment]
The folder was deleted in git but not on the file system. You could use alternative composer name to install the ext: `dmitryd/typo3-dd-googlesitemap`
