### ISSUE TITLE
Scheduler generated sitemap empty

### ISSUE THREAD

**Issue by toh82** [dmitryd/typo3-dd_googlesitemap#79]
Hello, dunno if this is an error but the sitemap file, generated with the scheduler is empty:

```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
</sitemapindex>
```

The sitemap on URL `index.php?eID=dd_googlesitemap` is, so far generated fine, except:
`error on line 3 at column 624706: Extra content at the end of the document`

Typo3: 6.2.19
dd_googlesitemap: 2.1.2

**Comment by dmitryd** [comment]
There is no support for user problems here. This place is only for bugs. Please, ask for help in mailing lists or slack channel.

**Comment by toh82** [comment]
@dmitryd so, you're saying that this a user issue ... okay that's strange on an extension with nearly no config. I posted that already to the slack, seems not interesting enough.

anyway, thanks

**Comment by dmitryd** [comment]
We use the same config in our company in every site we make and have no issue. We have several hundreds of sites currently active. No issue.

Most likely your home page is a shortcut page. In such case you need to read the manual.

**Comment by toh82** [comment]
Hmm, okay, Homepage isn't a shortcut, I checked already the manual while installing. 
Would not bother you with this, if I could think of a solution.

Maybe I'll do further research and debug it in the near future.

**Comment by dmitryd** [comment]
dd_googlesitemap should be able to obtain a list of **displayable** pages on the level below the root. See if this help
