### ISSUE TITLE
TYPO3 8.7.4 does not respect ['hidePagesIfNotTranslatedByDefault'] = 1

### ISSUE THREAD

**Issue by robsonrobi** [dmitryd/typo3-dd_googlesitemap#84]
Creating a page and do not localizing it, the page is printed in the sitemap.xml for the localization:

$GLOBALS['TYPO3_CONF_VARS']['FE']['hidePagesIfNotTranslatedByDefault'] = 1;

In the past, it worked fine.

Any suggestions ?

**Comment by dmitryd** [comment]
No idea.

**Comment by instruccionesaldorso** [comment]
@robsonrobi Did you find a solution for your issue?
I am using this setting as well for my L=1, and the pagetree is not shown completely when using example.com/index.php?eID=dd_googlesitemap&L=1

**Comment by dmitryd** [comment]
dd_googlesitemaps gets page tree using standard TYPO3 functions. There no magic of any kind. So if it worked in older TYPO3 versions and stopped working in 8.7.4, it must be a TYPO3 change that caused it.
