### ISSUE TITLE
Pages within a folder are ignored

### ISSUE THREAD

**Issue by GagaMen** [dmitryd/typo3-dd_googlesitemap#86]
Hi,
we have some problems with the sitemap generation and TYPO3 8.7.4. We are using your extension dd_googlesitemap v2.1.3 and a page tree structure like the following:

root page
-> main nav directory
---> page 1
---> page 2
---> page 3
---> page 4
---> page 5

The sitemap will be created without the pages inside the main nav directory. Did something change here? The same structure is working with TYPO3 7.6.X and dd_googlesitemap v2.1.3.

Thanx

**Comment by dmitryd** [comment]
You can examine changes to the extension from the home page of the project.

**Comment by GagaMen** [comment]
Hi,
I have seen there is an open pull request for it:
[Pull request #85](https://github.com/dmitryd/typo3-dd_googlesitemap/pull/85)
I tested his code and it works for me.
Thanx

**Comment by dmitryd** [comment]
Fixed. Thanks!
