### ISSUE TITLE
Creating scheduled task not possible

### ISSUE THREAD

**Issue by stweil** [dmitryd/typo3-dd_googlesitemap#87]
Creating the task "Generate offline sitemap" fails with an error message:

    Host is missing or does not match any of TYPO3 hosts from the installation.

That message is caused [here](https://github.com/dmitryd/typo3-dd_googlesitemap/blob/development/Classes/Scheduler/AdditionalFieldsProvider.php#L197) because the database table `sys_domain` is empty. An empty `sys_domain` table seems to be normal for installations with only a single domain, so I think it would be good if that case was handled.

**Comment by dmitryd** [comment]
You have to add the domain record. Otherwise it would be possible to use the extension to abuse other hosts by adding urls like `http://www.microsoft.com/?eID=dd_googlesitemap`. This is a safety feature.

**Comment by stweil** [comment]
Thank you. It now works for me after I added a domain record (see [documentation](https://wiki.typo3.org/Multidomain#STEP_2_-_Creating_the_domain_records)).

The current documentation mentions domain records, but does not say that a domain record is required for the task. Maybe this can be added.

**Comment by stweil** [comment]
Pull request #90 enhances the error message. Like that it would have helped me to find the right solution.

**Comment by dmitryd** [comment]
Could you make a pull request for this change? :)

**Comment by dmitryd** [comment]
Ah, I see it... Sorry.
