### ISSUE TITLE
Not working anymore on TYPO3 8?

### ISSUE THREAD

**Issue by echavaillaz** [dmitryd/typo3-dd_googlesitemap#89]
Hi Dmitry,

I have an issue with your ext on TYPO8. If I have a page tree like this: 

- rootpage (main entrypoint)
  - sysfolder (entrypoint for main nav)
    - page1
    - page2
  - sysfolder2 (entrypoint for sub nav)
    - page3

The sitemap outputs only the rootpage and don't take car of the pages in my other entry points.
In TYPO3 7 it is ok.

If I change my sysfolder to standard page, it is ok (but it is not recommend to make this if I use realurl)
Thanks

**Comment by stat1x** [comment]
I think it is related to #86

**Comment by dmitryd** [comment]
Closed because it is a duplicate.
