### ISSUE TITLE
Remove HTML-Tags from Title

### ISSUE THREAD

**Issue by stefanvar** [dmitryd/typo3-dd_googlesitemap#93]
Is it possible to remove HTML-Tags from tx_news.title in the sitemap?

Should be very easy with a strip_tags() around the title. Or is there another solution?

NewsSitemapRenderer (line 101)
`$content .= '<news:title>' . htmlspecialchars(strip_tags($title)) . '</news:title>';`

**Comment by dmitryd** [comment]
I believe that in the standard news configuration title is not supposed to have any html tags.

**Comment by dmitryd** [comment]
No feedback provided.
