### ISSUE TITLE
TYPO3 v9 compatibility (upcoming changes)

### ISSUE THREAD

**Issue by josefglatz** [dmitryd/typo3-dd_googlesitemap#96]
### TSFE method connectToDB() is deprecated

https://github.com/dmitryd/typo3-dd_googlesitemap/blob/development/Classes/Generator/EntryPoint.php#L82x

> https://review.typo3.org/56916

**Comment by dmitryd** [comment]
TYPO3 9.5.0 has its own sitemaps. This ext is not needed for v9.

**Comment by josefglatz** [comment]
Thx! And thank you 👍 for such a great extension even if it's not needed in v9
